title = "rusty-luau"
gitRepoUrl = "https://github.com/CompeyDev/rusty-luau"

gitSourceBranch = "main"
changelog = true

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = "/logo.png"
organizationName = "CompeyDev"
url = "https://rusty-luau.devcomp.xyz"
baseUrl = "/"
tagline = "Strongly typed implementations of various rust idioms in luau."

# TODO: Disable theme toggle
# [docusaurus.themeConfig.colorMode]
# defaultMode = "dark"
# disableSwitch = true
# respectPrefersColorScheme = false

[footer]
style = "light"
copyright = "Copyright Â© 2025 Erica Marigold."
